export const ARBEIDSGIVER_AVGIFT = 0.141;
export const ARBEIDSGIVER_AVGIFT_OVER_750 = 0.191;
export const SELSKAPSSKATT = 0.22;
export const UTBYTTESKATT = 0.378;
export const GRUNNBELOP = 111_477
export const MAKS_PENSJON_FOLKETRYGD = 7.1
export const MAKS_BELOEP_PENSJON = 12 // Pensjonssparing opp til maks 12G i lønnsinntekt
export const PAALAGT_PERMISJON_UKER = 15
export const FOEDSELSPERMISJON_FAR = 2
export const FOEDSELSPERMISJON_MOR = 3
export const TOTAL_WEEKS_OF_LEAVE = 49
export const TOTAL_SHARED_WEEKS = 16
